In [2]:
import numpy as np
a=np.array([5.6,'hello',7,4,6.7])
a.ndim
a.dtype

dtype('<U32')

1. a.ndim-gives the number of dimensions of the array as an integer value
2. a.shape-indicating the size of the array for each dimension
3. a.size-It gives the total number of elements of the array
4. a.dtype- is the data type of the elements of the array.
5. a.itemsize -specifies the size in bytes of each element of the array

In [15]:
p=np.array([[1,2], [3,4]], dtype=float)
p[1,0] #indexing

3.0

In [4]:
z=np.ones((2,3,4))
z

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [15]:
np.arange(10, 30, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [17]:
c=np.array([1, 2, 3, 4])
c[1:3]
c[::-1] #reverse an array

array([4, 3, 2, 1])

In [23]:
h=np.array([[2,3,4],[5,6,7],[3,4,5]])
h[0:2,2] #access elements of cloumn 2 in row 0 and 1 

array([4, 7])

In [24]:
h[1:3,0:3] #displays all 3 cloumns of last 2 rows 

array([[5, 6, 7],
       [3, 4, 5]])

In [25]:
h[:,2] #displays the last col

array([4, 7, 5])

# operations on array
1. arithmetic ar+ar1,-,*,@(matrix multiply),/,**,%
2. transpose
3. sort -1-D, for 2-D column-wise arr.sort(axis=0)
4. concatenate
5. reshaping
6. split
7. max,min
8. mean
9. dtd

In [29]:
# concatenate
n1=np.array([[8,4],[6,7]])
n2=np.zeros((3,2))
c=np.concatenate((n1,n2))
c

array([[8., 4.],
       [6., 7.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [39]:
#reshape
c.reshape(10)

array([8., 4., 6., 7., 0., 0., 0., 0., 0., 0.])

In [51]:
# max, min, sum
m1= np.max(c)
m3= np.max(c, axis=0) #find max element in each columns (axis=1 for each row)
m2 = np.min(c)
m4 = c.min(axis=1) # print min elements of each row
m5 = c.sum(axis=1) # sum each row
print(m1)
print(m2)
print(m3)
print(m4)
print(m5)

8.0
0.0
[8. 7.]
[4. 6. 0. 0. 0.]
[12. 13.  0.  0.  0.]


In [32]:
#sort ----> np.sort(array, axis, order, kind)

a = np.array([[3, 10, 2], [1, 5, 7], [2, 7, 5]])
a1 = np.sort(a) #row wise sorting
a2 = np.sort(a, axis = None)
a3 = np.sort(a, axis = 0) #column wise sorting

print(a1)
print(a2)
print(a3)

[[ 2  3 10]
 [ 1  5  7]
 [ 2  5  7]]
[ 1  2  2  3  5  5  7  7 10]
[[ 1  5  2]
 [ 2  7  5]
 [ 3 10  7]]


In [65]:
np.split(c,[3]) #split at index 3
np.split(c, [1,3]) #split at index 1 and 3

[array([[8., 4.]]),
 array([[6., 7.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]])]

In [66]:
# multiplication
a=np.array([[2,3],[3,4],[5,6]])
b=np.array([[2,3,4],[4,5,6]])
e=a.dot(b)
e

array([[16, 21, 26],
       [22, 29, 36],
       [34, 45, 56]])

In [67]:
numbers = np.array([0, 1, 3, 4])

#insert(arrayname,index,value[,axis])
array2 = np.insert(numbers, 2, 4) # insert 4 at index 2
print(array2)

[0 1 4 3 4]


In [68]:
array1 = np.array([0, 1, 2, 3])
array2 = np.array([4, 5, 6, 7])
array3 = np.insert(array1, 2, array2)
print(array3)

[0 1 4 5 6 7 2 3]


In [69]:
array1 = np.array([0, 1, 2, 3])
array2 = np.array([4, 5, 6, 7])

# insert values from array2 to array1 before given indices
array3 = np.insert(array1, [2, 3, 2, 1], array2)

print(array3)

[0 7 1 4 6 2 5 3]


In [70]:
c.transpose()

array([[8., 6., 0., 0., 0.],
       [4., 7., 0., 0., 0.]])

In [75]:
x = np.array([[10, 20, 30], [40, 50, 60]])
y = np.array([[100,200,300]])
print(np.append(x, y)) 

[ 10  20  30  40  50  60 100 200 300]
